# Reading in Files

In [1]:
import pandas as pd

In [22]:
df1 = pd.read_csv(r"C:\Users\shiva\jupyter\Alex Analyst Python\Web Scraping\output\Companies.csv")
df1

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology and cloud computing,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,Cencora,Pharmacy wholesale,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology and cloud computing,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive industry,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate and telecommunications,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Arlington County, Virginia"
60,61,StoneX Group,Financials,"66,036",55.3%,"4,000[2]","New York City, New York"
61,62,Lockheed Martin,Aerospace and defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology and cloud computing,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom hardware manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [19]:
df = pd.read_table(r"C:\Users\shiva\jupyter\Alex Analyst Python\Web Scraping\output\Companies.txt", encoding='latin1')  # You can also try 'cp1252' if 'latin1' doesn't work
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"6,11,289",6.70%,"21,00,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"5,13,983",9.40%,"15,40,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"4,13,680",44.80%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"3,94,328",7.80%,"1,64,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"3,24,162",12.70%,"4,00,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"3,22,467",10.40%,"2,59,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"3,02,089",9.40%,"3,83,000","Omaha, Nebraska"
7,8,Alphabet,Technology and cloud computing,"2,82,836",9.80%,"1,56,000","Mountain View, California"
8,9,McKesson Corporation,Health,"2,76,711",4.80%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"2,46,252",51.60%,"43,846","San Ramon, California"
10,11,Cencora,Pharmacy wholesale,"2,38,587",11.50%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"2,26,954",15.80%,"3,04,000","Issaquah, Washington"
12,13,Microsoft,Technology and cloud computing,"1,98,270",18.00%,"2,21,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"1,81,364",11.60%,"46,035","Dublin, Ohio"
14,15,Cigna,Health insurance,"1,80,516",3.70%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"1,80,012",27.60%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"1,75,702",53.00%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"1,71,189",58.00%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"1,58,057",15.90%,"1,73,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"1,57,403",4.10%,"4,71,600","Atlanta, Georgia"
20,21,General Motors,Automotive industry,"1,56,735",23.40%,"1,67,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"1,56,595",13.00%,"1,02,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"1,54,792",21.70%,"2,93,723","New York City, New York"
23,24,Kroger,Retail,"1,48,258",7.50%,"4,30,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"1,44,547",14.70%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"1,36,835",2.40%,"1,17,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"1,32,703",10.70%,"2,62,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"1,21,596",19.70%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"1,21,427",4.30%,"1,86,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate and telecommunications,"1,20,741",28.50%,"1,60,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"1,16,609",1.10%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"1,15,053",22.60%,"2,16,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"1,09,120",2.90%,"4,40,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"1,02,301",4.40%,"1,33,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"1,01,556",19.10%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"1,01,078",26.60%,"2,38,104","New York City, New York"
36,37,United Parcel Service,Transportation,"1,00,338",3.10%,"4,04,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"1,00,330",23.40%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.80%,"2,44,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.20%,"1,52,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.40%,"5,18,249","Memphis, Tennessee"
41,42,Humana,Health insurance,"92,870",11.80%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.30%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.60%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.60%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.70%,"3,15,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.50%,"2,38,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.70%,"1,95,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.90%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and energy,"81,462",51.40%,"1,27,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products manufacturing,"80,187",5.30%,"1,06,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.00%,"5,76,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.00%,"1,98,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.20%,"1,72,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.70%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.70%,"48,500","New York City, New York"
56,57,Sysco,Food service,"68,636",33.80%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.70%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.20%,"1,82,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.90%,"1,56,000","Arlington County, Virginia"
60,61,StoneX Group,Financials,"66,036",55.30%,"4,000[2]","New York City, New York"
61,62,Lockheed Martin,Aerospace and defense,"65,984",1.60%,"1,16,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.90%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.10%,"1,31,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.80%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.20%,"28,500","Clearwater, Florida"
66,67,IBM,Technology and cloud computing,"60,530",16.30%,"3,03,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.50%,"2,50,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.30%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.60%,"1,09,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.80%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and logistics,"59,043",88.40%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.20%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.60%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.30%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.30%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.50%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.40%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.30%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.50%,"2,42,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.50%,"1,01,700","Stamford, Connecticut"
81,82,Tyson Foods,Food processing,"53,282",13.20%,"1,42,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.40%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom hardware manufacturing,"51,557",3.50%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.60%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.40%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.20%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.60%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.90%,"3,29,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.00%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.90%,"1,29,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.30%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food processing,"47,194",61.60%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.80%,"3,616","Parsippany??Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.90%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.60%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.50%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.50%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.50%,"1,30,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.70%,"51,000","San Diego, California"

In [20]:
df = pd.read_excel(r"C:\Users\shiva\jupyter\Alex Analyst Python\Web Scraping\output\Nashville Housing Data for Data Cleaning.xlsx")
df

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE",2015-05-27,157500,20150608-0053286,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56473,27707,188 10 0A 107.00,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE",2015-03-02,145000,20150304-0019013,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE",2016-08-16,234611,20160819-0087214,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE",2016-09-07,93844,20160919-0098411,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
pd.set_option('display.max.rows', 100)

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    100 non-null    int64
 1   Name                    100 non-null    object
 2   Industry                100 non-null    object
 3   Revenue (USD millions)  100 non-null    object
 4   Revenue growth          100 non-null    object
 5   Employees               100 non-null    object
 6   Headquarters            100 non-null    object
dtypes: int64(1), object(6)
memory usage: 5.6+ KB

In [24]:
df1.shape

(100, 7)

In [26]:
df1.head(10)

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology and cloud computing,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"

In [27]:
df1['Rank']

0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12
12     13
13     14
14     15
15     16
16     17
17     18
18     19
19     20
20     21
21     22
22     23
23     24
24     25
25     26
26     27
27     28
28     29
29     30
30     31
31     32
32     33
33     34
34     35
35     36
36     37
37     38
38     39
39     40
40     41
41     42
42     43
43     44
44     45
45     46
46     47
47     48
48     49
49     50
50     51
51     52
52     53
53     54
54     55
55     56
56     57
57     58
58     59
59     60
60     61
61     62
62     63
63     64
64     65
65     66
66     67
67     68
68     69
69     70
70     71
71     72
72     73
73     74
74     75
75     76
76     77
77     78
78     79
79     80
80     81
81     82
82     83
83     84
84     85
85     86
86     87
87     88
88     89
89     90
90     91
91     92
92     93
93     94
94     95
95     96
96     97
97     98
98     99
99    100
Name: Rank, dtype: int64

In [29]:
df1.loc[55]

Rank                                           56
Name                                Goldman Sachs
Industry                               Financials
Revenue (USD millions)                     68,711
Revenue growth                               5.7%
Employees                                  48,500
Headquarters              New York City, New York
Name: 55, dtype: object

In [30]:
df1.iloc[55]

Rank                                           56
Name                                Goldman Sachs
Industry                               Financials
Revenue (USD millions)                     68,711
Revenue growth                               5.7%
Employees                                  48,500
Headquarters              New York City, New York
Name: 55, dtype: object